import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import { BackgroundSyncProvider, QueryProvider, ThemeProvider, Header, AppSidebar, } from "@/components/shared";
import { SidebarInset, SidebarProvider } from "@/components/ui";

import "./globals.css";	

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Steam Portfolio",
	description: "Generated by create next app",
};

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
				<QueryProvider>
					<BackgroundSyncProvider>
						<ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
							<SidebarProvider>
								<AppSidebar />
								<SidebarInset className="overflow-x-auto">
									<Header />
									<div className="p-2 2k:p-2.5 4k:p-4 8k:p-8">
										{children}
									</div>
								</SidebarInset>
							</SidebarProvider>
						</ThemeProvider>
					</BackgroundSyncProvider>
				</QueryProvider>
			</body>
		</html>
	)
}