import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import { AppSidebar, AppBreadcrumb } from "@/components/shared";
import { Separator, SidebarProvider, SidebarTrigger } from "@/components/ui";

import "./globals.css";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children, }: Readonly<{ children: React.ReactNode; }>) {
	return (
		<html lang="en">
			<body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
				<SidebarProvider className="grid grid-cols-[auto_1fr] grid-rows-[auto_1fr]">
					<AppSidebar className="row-span-2" />
					<header className="header col-start-2 flex">
						<SidebarTrigger />
						<Separator orientation={"vertical"} />
						<AppBreadcrumb />
						<Separator orientation={"vertical"} />
					</header>
					<main className="main col-start-2 h-full">
						{children}
					</main>
				</SidebarProvider>
			</body>
		</html>
	);
}